STATE_DIC = {
        'ALASKA': 'AK',
        'ALABAMA': 'AL',
        'ARKANSAS': 'AR',
        'ARIZONA': 'AZ',
        'CALIFORNIA': 'CA',
        'COLORADO': 'CO',
        'CONNECTICUT': 'CT',
        'DISTRICT OF COLUMBIA': 'DC', 
        'DELAWARE': 'DE',
        'FLORIDA': 'FL', 
        'GEORGIA': 'GA',
        'HAWAII': 'HI',
        'IOWA': 'IA',
        'IDAHO': 'ID',
        'ILLINOIS': 'IL',
        'INDIANA': 'IN',
        'KANSAS': 'KS',
        'KENTUCKY': 'KY',
        'LOUISIANA': 'LS',
        'MASSACHUSETTS': 'MA',
        'MARYLAND': 'MD',
        'MAINE': 'ME',
        'MICHIGAN': 'MI',
        'MINNESOTA': 'MN',
        'MISSOURI': 'MO',
        'MISSISSIPPI': 'MS',
        'MONTANA': 'MT',
        'NORTH CAROLINA': 'NC',
        'NORTH DAKOTA': 'ND',
        'NEBRASKA': 'NE',
        'NEW HAMPSHIRE': 'NH',
        'NEW JERSEY': 'NJ',
        'NEW MEXICO': 'NM',
        'NEVADA':'NV',
        'NEW YORK': 'NY',
        'OHIO': 'OH',
        'OKLAHOMA': 'OK',
        'OREGON': 'OR',
        'PENNSYLVANIA': 'PA',
        'RHODE ISLAND': 'RI',
        'SOUTH CAROLINA': 'SC',
        'SOUTH DAKOTA': 'SD',
        'TENNESSEE': 'TN',
        'TEXAS': 'TX',
        'UTAH': 'UT',
        'VIRGINIA': 'VA',
        'VERMONT': 'VT',
        'WASHINGTON': 'WA',
        'WISCONSIN': 'WI',
        'WEST VIRGINIA': 'WV',
        'WYOMING': 'WY',
        }

STATE_SET = set(["HI", "AK", "FL", "SC", "GA", "AL", "NC", "TN", "RI", "CT", "MA",
    "ME", "NH", "VT", "NY", "NJ", "PA", "DE", "MD", "WV", "KY", "OH", 
    "MI", "WY", "MT", "ID", "WA", "DC", "TX", "CA", "AZ", "NV", "UT", 
    "CO", "NM", "OR", "ND", "SD", "NE", "IA", "MS", "IN", "IL", "MN", 
    "WI", "MO", "AR", "OK", "KS", "LS", "VA"]);
